services:

  gzdoom:
    container_name: gzdoom
    image: gzdoom
    network_mode: none
    volumes:
      - $HOME/.local/share/games/doom/:/home/user/.local/share/games/doom/
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /dev/dri/card1:/dev/dri/card1
      - $HOME/.config/gzdoom/:/home/user/.config/gzdoom/
      - /run/user/1000/pulse:/run/user/1000/pulse 
    environment:
      - DISPLAY=$DISPLAY
      - DOOMWADDIR=/home/user/.local/share/games/doom/
