#!/bin/bash

docker run \
  -d \
  --rm \
  -e DISPLAY=${DISPLAY} \
  -v /tmp/.X11-unix:/tmp/.X11-unix \
  -v $HOME:/home/user/ \
  --network none \
  --name audacity \
  -v /dev/snd:/dev/snd \
  --privileged \
  audacity:latest
  
