#!/bin/bash

USER_ID=$(id -u)

docker run \
  -e DISPLAY=${DISPLAY} \
  -d \
  --rm \
  --network none \
  --name audacity \
  -v $HOME:/home/user/ \
  -v /dev/snd:/dev/snd \
  -v /tmp/.X11-unix:/tmp/.X11-unix \
  -v /dev/dri/card1:/dev/dri/card1 \
  -v /run/user/${USER_ID}/pulse:/run/user/1000/pulse \
  --privileged \
  audacity:latest
  
