#!/bin/bash

docker run --rm \
  -d \
  -e DISPLAY=${DISPLAY} \
  -v /tmp/.X11-unix:/tmp/.X11-unix \
  -v /var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket:rw \
  -v brave:/home/user/ \
  --security-opt seccomp=./chrome.json \
  --device /dev/dri \
  brave-browser:latest
  
