#!/bin/bash

docker start 1password ||
docker run \
  -d \
  -e DISPLAY=${DISPLAY} \
  -v /tmp/.X11-unix:/tmp/.X11-unix \
  --name 1password \
  -v /dev/snd:/dev/snd \
  -v /run/dbus/system_bus_socket:/run/dbus/system_bus_socket \
  --privileged \
  1password:latest