services:

  1password:
    image: 1password
    container_name: 1password
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix 
      - /dev/snd:/dev/snd
      - /run/dbus/system_bus_socket:/run/dbus/system_bus_socket
    networks:
      - 1password
    privileged: true

networks:
  1password:
    driver: bridge